-- MySQL Script generated by MySQL Workbench
-- 10/25/14 19:51:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dudente
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dudente` ;

-- -----------------------------------------------------
-- Schema dudente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dudente` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `dudente` ;

-- -----------------------------------------------------
-- Table `Plano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Plano` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Plano` (
  `Id_Plano` INT NOT NULL,
  `Nome_Plano` VARCHAR(45) NOT NULL,
  `Dt_Val_Plano` DATETIME NOT NULL,
  PRIMARY KEY (`Id_Plano`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Paciente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Paciente` (
  `id_Paciente` INT NOT NULL,
  `Nome_Paciente` VARCHAR(45) NOT NULL,
  `Idade_Paciente` INT NULL,
  `Plano_Id_Plano` INT NOT NULL,
  PRIMARY KEY (`id_Paciente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Dentista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dentista` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Dentista` (
  `id_Funcionario` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Salario_Dentista` VARCHAR(45) NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `Espec_Dentista` VARCHAR(100) NULL,
  PRIMARY KEY (`id_Funcionario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Secretaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Secretaria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Secretaria` (
  `id_Funcionario` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Salario` DOUBLE NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `Bonificacao_Secretaria` DOUBLE NULL,
  PRIMARY KEY (`id_Funcionario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medicamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Medicamento` (
  `id_Medicamento` INT NOT NULL,
  `Nome_Medicamento` VARCHAR(60) NOT NULL,
  `Dt_Val_Medicamento` DATETIME NOT NULL,
  PRIMARY KEY (`id_Medicamento`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Aparelho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aparelho` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Aparelho` (
  `id_Aparelho` INT NOT NULL,
  `Nome_Aparelho` VARCHAR(60) NOT NULL,
  `Dt_Man_Aparelho` DATETIME NULL,
  PRIMARY KEY (`id_Aparelho`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compra` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Compra` (
  `id_Compra` INT NOT NULL,
  `Dt_Compra` DATETIME NOT NULL,
  `Val_Compra` DOUBLE NULL,
  `Medicamento_id_Medicamento` INT NOT NULL,
  `Aparelho_id_Aparelho` INT NOT NULL,
  PRIMARY KEY (`id_Compra`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Procedimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Procedimento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Procedimento` (
  `id_Procedimento` INT NOT NULL,
  `Nome_Procedimento` VARCHAR(60) NOT NULL,
  `Tipo_Procedimento` VARCHAR(1) NULL,
  `Dc_Procedimento` VARCHAR(500) NULL,
  `Dt_Procedimento` DATETIME NULL,
  `Obs_Procedimento` VARCHAR(500) NULL,
  `Diagnostico_Procedimento` VARCHAR(500) NULL,
  `Tipo_Cir_Procedimento` VARCHAR(100) NULL,
  `Tipo_Ort_Odont_Procedimento` VARCHAR(100) NULL,
  `Resultado_Procedimento` VARCHAR(500) NULL,
  PRIMARY KEY (`id_Procedimento`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Clinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Clinica` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Clinica` (
  `id_Clinica` INT NOT NULL,
  `Nome_Clinica` VARCHAR(45) NOT NULL,
  `Endereco_Clinica` VARCHAR(60) NULL,
  `Compra_id_Compra` INT NOT NULL,
  `id_Procedimento` INT NOT NULL,
  `id_Funcionario` INT NOT NULL,
  `id_Paciente` INT NOT NULL,
  PRIMARY KEY (`id_Clinica`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
